import { FileText, GraduationCap, Users, BookOpen, Wallet, Download } from "lucide-react";
import { LineChart, Line, XAxis, ResponsiveContainer, Tooltip, PieChart, Pie, Cell } from "recharts";
import Banner from "../components/Banner";
import StatCard from "../components/StatCard";
import Card from "../components/Card";

const trend = [
  { m: "Mar", students: 90, exams: 60, fees: 40, attendance: 30 },
  { m: "Apr", students: 110, exams: 70, fees: 55, attendance: 40 },
  { m: "May", students: 130, exams: 85, fees: 65, attendance: 48 },
  { m: "Jun", students: 150, exams: 95, fees: 78, attendance: 55 },
  { m: "Jul", students: 175, exams: 110, fees: 90, attendance: 62 },
  { m: "Aug", students: 210, exams: 140, fees: 110, attendance: 70 },
];

const dist = [
  { name: "Academic", value: 35, color: "#2F6FED" },
  { name: "Attendance", value: 25, color: "#8B5CF6" },
  { name: "Fee", value: 15, color: "#12B981" },
  { name: "Examination", value: 15, color: "#F5A524" },
  { name: "Others", value: 10, color: "#EC4899" },
];

const recent = [
  { name: "Class Performance Report", type: "Academic", by: "Ayesha Khan", date: "Aug 12, 2026" },
  { name: "Attendance Summary", type: "Attendance", by: "Ahmed Ali", date: "Aug 11, 2026" },
  { name: "Fee Collection Report", type: "Fee", by: "Fatima Noor", date: "Aug 10, 2026" },
  { name: "Exam Results Report", type: "Examination", by: "Bilal Ahmed", date: "Aug 8, 2026" },
];

const types = [
  { label: "Academic Report", sub: "View & download academic reports", color: "#2F6FED" },
  { label: "Attendance Report", sub: "View attendance summaries", color: "#12B981" },
  { label: "Fee Report", sub: "Check fee collection & dues", color: "#F5A524" },
  { label: "Exam Report", sub: "Get exam results & analysis", color: "#8B5CF6" },
  { label: "Student Report", sub: "Generate student progress reports", color: "#EC4899" },
  { label: "Teacher Report", sub: "View teacher performance", color: "#12B981" },
];

export default function Reports() {
  return (
    <>
      <Banner title="Reports & Analytics" subtitle="Get detailed insights into your school's performance with comprehensive reports and real-time data." tagline={"Data Today\nBetter Decisions Tomorrow"} />

      <div className="grid grid-cols-5 gap-4 mb-5">
        <StatCard icon={<FileText size={16} />} iconBg="#2F6FED" label="Total Reports" value="24" delta="12% vs last month" />
        <StatCard icon={<GraduationCap size={16} />} iconBg="#8B5CF6" label="Student Reports" value="12" delta="8% vs last month" />
        <StatCard icon={<Users size={16} />} iconBg="#12B981" label="Teacher Reports" value="6" delta="20% vs last month" />
        <StatCard icon={<BookOpen size={16} />} iconBg="#F5A524" label="Exam Reports" value="4" delta="33% vs last month" />
        <StatCard icon={<Wallet size={16} />} iconBg="#EC4899" label="Fee Reports" value="2" delta="50% vs last month" />
      </div>

      <div className="grid grid-cols-[2fr_1fr] gap-4 mb-4">
        <Card title="Report Overview">
          <ResponsiveContainer width="100%" height={190}>
            <LineChart data={trend}>
              <XAxis dataKey="m" tick={{ fontSize: 11, fill: "#6B7590" }} axisLine={false} tickLine={false} />
              <Tooltip />
              <Line type="monotone" dataKey="students" stroke="#2F6FED" strokeWidth={2.5} dot={{ r: 2 }} />
              <Line type="monotone" dataKey="exams" stroke="#8B5CF6" strokeWidth={2} dot={{ r: 2 }} />
              <Line type="monotone" dataKey="fees" stroke="#12B981" strokeWidth={2} dot={{ r: 2 }} />
              <Line type="monotone" dataKey="attendance" stroke="#F5A524" strokeWidth={2} dot={{ r: 2 }} />
            </LineChart>
          </ResponsiveContainer>
        </Card>
        <Card title="Report Distribution">
          <div className="relative flex items-center justify-center h-[130px]">
            <ResponsiveContainer width={130} height={130}>
              <PieChart>
                <Pie data={dist} dataKey="value" innerRadius={40} outerRadius={60}>
                  {dist.map((d) => <Cell key={d.name} fill={d.color} />)}
                </Pie>
              </PieChart>
            </ResponsiveContainer>
            <div className="absolute text-center"><div className="font-heading font-bold text-xl">24</div><div className="text-[10px] text-muted">Reports</div></div>
          </div>
        </Card>
      </div>

      <div className="grid grid-cols-[2fr_1fr] gap-4">
        <Card title="Recent Reports">
          <table className="w-full text-[13px]">
            <thead>
              <tr className="text-left text-muted text-[11.5px] uppercase border-b border-border">
                <th className="py-2.5">Report</th><th>Type</th><th>Generated By</th><th>Date</th><th></th>
              </tr>
            </thead>
            <tbody>
              {recent.map((r) => (
                <tr key={r.name} className="border-b border-border last:border-none row-hover">
                  <td className="py-2.5 font-semibold">{r.name}</td>
                  <td>{r.type}</td>
                  <td>{r.by}</td>
                  <td>{r.date}</td>
                  <td><Download size={15} className="text-brand-blue" /></td>
                </tr>
              ))}
            </tbody>
          </table>
        </Card>
        <Card title="Report Types">
          <div className="grid grid-cols-2 gap-2.5">
            {types.map((t) => (
              <div key={t.label} className="bg-bg rounded-xl p-3 cursor-pointer hover:bg-blue-50">
                <div className="text-[12.5px] font-semibold" style={{ color: t.color }}>{t.label}</div>
                <div className="text-[11px] text-muted mt-0.5">{t.sub}</div>
              </div>
            ))}
          </div>
        </Card>
      </div>
    </>
  );
}
